const F_TAG_LIB = "tags.json" // File: Name of tag library file tags.json
const T_SITES = "Sites" // Tag prop name: "Sites"
const T_ACC = "Actresses" // Tag prop name: "Actresses"
const T_TAGLIST = "Taglist" // Tag prop name: "Taglib"
const T_TL_NAME = "Name" // Tag prop name: "Taglib" ["Name"]
const T_TL_DESC = "Description" // Tag prop name: "Taglib" ["Description"]
const T_TL_MEMBERS = "Members" // Tag prop name: "Taglib" ["Members"]
const T_TYPE_SITE = "S" // Tag type: Site
const T_TYPE_ACT = "A" // Tag type: Actress
const T_TYPE_TAG = "T" // Tag type: Normal tag